### ISSUE TITLE
%logger name% causes severe errors to log to console

### ISSUE THREAD

**Issue by kohy-creates** [Blueyescat/skript-logs#1]
**Well, title explains everything**

**Steps to Reproduce**
```
on log:
    set {_log} to logger name
```

**Expected Behavior**
{_log} will be set to name of logger

**Errors / Screenshots**
```
[17:59:13 ERROR]: #!#! [Skript] Severe Error:
[17:59:12 ERROR]: #!#!   Skript: 2.5.3 (latest)
[17:59:13 ERROR]: #!#!
[17:59:12 ERROR]: #!#!     Flavor: skriptlang-github
[17:59:13 ERROR]: #!#! Something went horribly wrong with Skript.
[17:59:12 ERROR]: #!#!     Date: 2020-12-11
[17:59:13 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[17:59:13 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[17:59:13 ERROR]: #!#! Following plugins are probably related to this error in some way:
[17:59:12 ERROR]: #!#!   Bukkit: 1.16.4-R0.1-SNAPSHOT
[17:59:13 ERROR]: #!#! skript-logs (https://github.com/Blueyescat/skript-logs)
[17:59:12 ERROR]: #!#!   Minecraft: 1.16.4
[17:59:13 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[17:59:12 ERROR]: #!#!   Java: 1.8.0_51 (Java HotSpot(TM) 64-Bit Server VM 25.51-b03)
[17:59:13 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[17:59:12 ERROR]: #!#!   OS: Windows 8.1 amd64 6.3
[17:59:13 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[17:59:12 ERROR]: #!#!
[17:59:13 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[17:59:12 ERROR]: #!#! Server platform: Paper
[17:59:13 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[17:59:13 ERROR]: #!#!
[17:59:13 ERROR]: #!#! Stack trace:
[17:59:12 ERROR]: #!#!
[17:59:13 ERROR]: #!#! java.lang.NullPointerException
[17:59:12 ERROR]: #!#! Current node: null
[17:59:13 ERROR]: #!#!     at me.blueyescat.skriptlogs.skript.expressions.ExprLoggerName.get(ExprLoggerName.java:44)
[17:59:12 ERROR]: #!#! Current item: set {_log}(as java.lang.Object) to logged message
[17:59:13 ERROR]: #!#!     at me.blueyescat.skriptlogs.skript.expressions.ExprLoggerName.get(ExprLoggerName.java:23)
[17:59:12 ERROR]: #!#! Current trigger: log (log) (diskord.sk, line 46)
[17:59:13 ERROR]: #!#!     at ch.njol.skript.lang.util.SimpleExpression.getArray(SimpleExpression.java:100)
[17:59:13 ERROR]: #!#!     at ch.njol.skript.effects.EffChange.execute(EffChange.java:276)
[17:59:13 ERROR]: #!#!     at ch.njol.skript.lang.Effect.run(Effect.java:51)
[17:59:12 ERROR]: #!#!
[17:59:13 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:60)
[17:59:12 ERROR]: #!#! Thread: Server thread
[17:59:13 ERROR]: #!#!     at ch.njol.skript.lang.TriggerItem.walk(TriggerItem.java:88)
[17:59:12 ERROR]: #!#!
[17:59:13 ERROR]: #!#!     at ch.njol.skript.lang.Trigger.execute(Trigger.java:56)
[17:59:12 ERROR]: #!#! Language: english
[17:59:13 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler.check(SkriptEventHandler.java:153)
[17:59:12 ERROR]: #!#! Link parse mode: DISABLED
[17:59:13 ERROR]: #!#!     at ch.njol.skript.SkriptEventHandler$1.execute(SkriptEventHandler.java:111)
[17:59:12 ERROR]: #!#!
[17:59:13 ERROR]: #!#!     at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[17:59:12 ERROR]: #!#! End of Error.
[17:59:13 ERROR]: #!#!     at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[17:59:12 ERROR]: #!#!
[17:59:13 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[17:59:12 ERROR]: #!#!
[17:59:13 ERROR]: #!#!     at me.blueyescat.skriptlogs.util.LogAppender$1.run(LogAppender.java:27)
```

**Server Information**
* Server Platform:
* Skript: 2.5.3 (latest)
* skript-logs: latest
* Bukkit:  1.16.4-R0.1-SNAPSHOT
* Minecraft: 1.16.4
* Java: 1.8.0_51
* Operating System: Windows 10

**Comment by JewishLewish** [comment]
https://skripthub.net/docs/?addon=skript-logs

Try looking at their documentation.
